export const Products = [
    {id: '1',
    category:'C1', 
    title: 'Producto 1',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1500'},
    {id: '2',
    category:'C2', 
    title: 'Producto 2',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '800'},
    {id: '3',
    category:'C3', 
    title: 'Producto 3',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1000'},
    {id: '4',
    category:'C4', 
    title: 'Producto 4',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '650'},
    {id: '5',
    category:'C1', 
    title: 'Producto 5',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1200'},
    {id: '6',
    category:'C2', 
    title: 'Producto 6',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '700'},
    {id: '7',
    category:'C3', 
    title: 'Producto 7',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1300'},
    {id: '8',
    category:'C4', 
    title: 'Producto 8',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '2000'},
    {id: '9',
    category:'C1', 
    title: 'Producto 9',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1500'},
    {id: '10',
    category:'C2', 
    title: 'Producto 10',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '900'},
    {id: '11',
    category:'C3', 
    title: 'Producto 11',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1400'},
    {id: '12',
    category:'C4', 
    title: 'Producto 12',  
    url: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
    price: '1350'}
  ]